import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ThemeProvider from "@/provider/ThemeProvider";

import "../styles/globals.css";
import WebVitals from "@/components/WebVitals/WebVitals";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ThemeProvider>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>
					<WebVitals />
					{children}
				</body>
			</ThemeProvider>
		</html>
	);
}
